apiVersion: v1
kind: Service
metadata:
  name: my-react-app
spec:
  selector:
    app: my-react-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-react-app
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
        - name: my-react-app
          image: anujkumar96/my-react-app:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
